config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'armstrong/input'
  get 'armstrong', to: redirect('armstrong/input')
  get 'armstrong/result', as: :result_armstrong
  get 'armstrong/inspect_db'

  root 'armstrong#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armstrong.rb
# frozen_string_literal: true

class Armstrong < ApplicationRecord
  validates :digits, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/armstrong_controller.rb
# frozen_string_literal: true

class ArmstrongController < ApplicationController
  def input; end

  def result
    @n = params[:number].to_i
    if @n < 1
      flash[:alert] = "There are't numbers with #{@n} digits"
      redirect_to armstrong_path
      return
    end

    if @n > 39
      @result = []
      return
    end

    if @n > 10
      flash[:alert] = 'Very big number of digits. My computer will brake =('
      redirect_to armstrong_path
      return
    end

    res = Armstrong.find_by(digits: @n)
    if !res.nil?
      @result = ActiveSupport::JSON.decode(res.numbers)
    else
      @result = (10**(@n - 1)).upto(10**@n - 1).select do |num|
        num.digits.reduce(0) { |sum, dig| sum + dig**@n }.equal? num
      end

      unless @result.empty?
        res = Armstrong.new digits: @n, numbers: ActiveSupport::JSON.encode(@result)
        res.save
      end
    end
  end

  def inspect_db
    respond_to do |format|
      @numbers = Armstrong.all
      format.xml { render xml: @numbers }
      format.json { render json: @numbers }
      format.html {}
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/armstrong_helper.rb
# frozen_string_literal: true

module ArmstrongHelper
end

app/views/armstrong/index.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-md-8 offset-md-2 center">
      <h1>Armstrong number</h1>
      <div class="jumbotron">
        In recreational number theory, a narcissistic number (also known as a pluperfect digital invariant (PPDI), an Armstrong number (after Michael F. Armstrong) or a plus perfect number) is a number that is the sum of its own digits each raised to the power of the number of digits. This definition depends on the base b of the number system used, e.g., b = 10 for the decimal system or b = 2 for the binary system.
      </div>
      <%= content_tag 'a', "Let's calculate some of them", role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>

app/views/armstrong/input.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4" align="center">
      <h1>Armstrong numbers</h1>
      <%= bootstrap_form_tag url: result_armstrong_path, method: 'get' do |f| %>
        <% if flash[:alert] %>
          <%= f.number_field :number, label: 'Number of digits in number', class: 'is-invalid'%>
          <%= f.label flash[:alert], class: 'text-danger' %>
        <% else %>
          <%= f.number_field :number, label: 'Number of digits in number'%>
        <% end %>
        <%= f.primary 'Show numbers'%>
      <% end %>
    </div>
  </div>
</div>

app/views/armstrong/inspect_db.html.erb
<h3>Choose xml format</h3>
<%= @numbers.to_json %>

app/views/armstrong/result.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <h1><%= "Armstrong numbers with #{@n} digits" %></h1>
      <% if @result.empty? %>
        <div class="alert alert-danger" role="alert"><%= "There are't armstrong numbers with #{@n} digits" %></div>
      <% else %>
        <table class="table table-bordered table-hover bg-white">
          <thead class="thead-dark">
          <tr>
            <th>№</th>
            <th >Armstrong number</th>
          </tr>
          </thead>
          <tbody>
          <% @result.each_with_index do |num, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%= num %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% end %>
      <%= content_tag 'a', 'Go back', role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <span class="text-muted">Suldin Aleksandr, 2018</span>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <!-- Brand/logo -->
    <%= content_tag :a, 'Armstrong', class: 'navbar-brand', href: root_path %>

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= content_tag :a, 'Calculate', class: 'nav-link', href: armstrong_path %>
      </li>
      <li class="nav-item">
        <%= content_tag :a, 'DataBase inspect', class: 'nav-link', href: armstrong_inspect_db_path(format: :json) %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lr11</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



</head>

<body class="bg-light">
<%= render 'layouts/header' %>
<main class="container" role="main">
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
</body>
</html>